/* Candy Editorial Studio: 150 collectible category cards with matched image moods and soft candy accents. */
export type CategoryCard = { id: number; title: string; description: string; kind: string; image: string; accent: string; duration: string };

const imagePool = {
  story: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=700&q=82",
  nature: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=82",
  ocean: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=700&q=82",
  food: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=82",
  fashion: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=700&q=82",
  studio: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=700&q=82",
  city: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=700&q=82",
  learn: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=700&q=82",
  celebration: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=700&q=82",
  wellness: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=700&q=82",
  tech: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=700&q=82",
  abstract: "https://images.unsplash.com/photo-1557682250-33bd709cbe85?auto=format&fit=crop&w=700&q=82",
};

const titles = [
  "3D Cartoon Stories", "Baby Bedtime Stories", "Nursery Rhymes", "Kids Adventure Stories", "Fairy Tales", "Animal Fables", "Reverse Animal World", "Claymation Stories", "Stop-Motion Stories", "Puppet Theatre", "Anime Adventures", "Manga Action Scenes", "Superhero Origin Stories", "Princess Quests", "Toy Shop Adventures", "Magical School Stories", "Friendship Stories", "Family Stories", "School Day Stories", "Moral Lesson Stories",
  "Cinematic Drama", "Romantic Short Film", "Historical Drama", "Period Film", "Mystery Thriller", "Psychological Thriller", "Crime Investigation", "Horror Story", "Supernatural Horror", "Found Footage Horror", "Comedy Sketch", "Romantic Comedy", "Workplace Comedy", "Mockumentary", "Action Sequence", "Chase Scene", "Heist Film", "Survival Film", "Coming-of-Age Film", "Quiet Human Drama",
  "Epic Fantasy", "Fantasy Quest", "Dragon Adventure", "Mythology Retelling", "Fairy Kingdom", "Wizard Academy", "Time Travel Story", "Parallel Universe", "Space Opera", "Cyberpunk City", "Robot Companion", "Alien First Contact", "Mars Expedition", "Post-Apocalyptic Journey", "Underwater Civilization", "Steampunk Adventure", "Time-Loop Mystery", "Virtual Reality Story", "AI Companion Story", "Future City Tour",
  "English Beginner Lesson", "English Conversation Practice", "English Pronunciation", "English Vocabulary", "English Grammar", "English Travel Phrases", "English Job Interview", "English Storytelling", "English Listening Practice", "English Kids Lesson", "Math Explainer", "Science Experiment", "Physics Demonstration", "Chemistry Explainer", "Biology Lesson", "Astronomy Lesson", "Coding Tutorial", "Digital Safety Lesson", "Study Skills", "Exam Preparation",
  "Workplace Onboarding", "Safety Training", "Leadership Training", "Communication Training", "Customer Service Training", "Sales Training", "Time Management", "Teamwork Workshop", "Conflict Resolution", "Diversity Training", "Product Tutorial", "Software Walkthrough", "DIY Home Repair", "Woodworking Tutorial", "Craft Tutorial", "Drawing Tutorial", "Photography Tutorial", "Video Editing Tutorial", "Cooking Tutorial", "Gardening Tutorial",
  "Travel Vlog", "City Guide", "Hidden Places Travel", "Solo Travel Diary", "Food Travel Vlog", "Road Trip Film", "Train Journey Vlog", "Island Escape", "Mountain Trek", "Cultural Festival Vlog", "Daily Life Vlog", "Day-in-the-Life", "Morning Routine", "Night Routine", "Creator Studio Vlog", "Behind the Scenes", "Personal Growth Vlog", "Study With Me", "Fitness Vlog", "Family Vlog",
  "Wildlife Documentary", "Ocean Documentary", "Rainforest Documentary", "Desert Documentary", "Mountain Documentary", "Birdwatching Film", "Insect Macro Film", "Pet Story", "Conservation Campaign", "Climate Explainer", "History Documentary", "Ancient Civilizations", "Archaeology Story", "Biography Documentary", "Science Documentary", "Medical Explainer", "Mental Health Education", "Nutrition Education", "Fitness Training", "Meditation Guide",
  "Product Advertisement", "Beauty Product Film", "Skincare Commercial", "Fashion Campaign", "Luxury Brand Film", "Tech Product Launch", "App Promo Video", "E-commerce Product Demo", "Unboxing Video", "Food Commercial", "Automotive Commercial", "Real Estate Walkthrough", "Restaurant Promo", "Event Promo", "Music Video", "Dance Performance", "Concert Visuals", "Sports Highlight Reel", "Startup Pitch Video", "Social Awareness Campaign"
];

const accents = ["coral", "aqua", "yellow", "lilac", "peach", "mint", "rose"];
const chooseImage = (title: string) => { const t = title.toLowerCase(); if (/(cartoon|story|fairy|anime|manga|superhero|princess|toy|puppet|kids|baby|nursery)/.test(t)) return imagePool.story; if (/(ocean|island|underwater|bird|insect|wildlife|rainforest|desert|mountain|nature|climate|conservation)/.test(t)) return imagePool.ocean; if (/(food|cooking|restaurant|nutrition)/.test(t)) return imagePool.food; if (/(fashion|beauty|skincare|luxury)/.test(t)) return imagePool.fashion; if (/(workplace|training|office|leadership|communication|sales|teamwork|onboarding|customer)/.test(t)) return imagePool.studio; if (/(english|lesson|math|science|physics|chemistry|biology|astronomy|coding|study|exam|tutorial|education|explainer)/.test(t)) return imagePool.learn; if (/(festival|event|concert|dance|music|celebration)/.test(t)) return imagePool.celebration; if (/(meditation|mental|fitness|wellness|routine|growth)/.test(t)) return imagePool.wellness; if (/(tech|app|software|ai|robot|cyberpunk|virtual|digital|startup)/.test(t)) return imagePool.tech; if (/(city|travel|road|train|vlog|real estate|automotive)/.test(t)) return imagePool.city; if (/(fantasy|space|alien|mars|future|time|myth|dragon|wizard|steampunk)/.test(t)) return imagePool.abstract; return imagePool.nature; };
const chooseKind = (title: string) => { const t = title.toLowerCase(); if (/(lesson|training|tutorial|education|explainer|practice|preparation)/.test(t)) return "Learn"; if (/(commercial|advertisement|promo|campaign|launch|demo|unboxing|pitch)/.test(t)) return "Create"; if (/(vlog|diary|routine|day-in-the-life)/.test(t)) return "Vlog"; if (/(documentary|history|biography|archaeology)/.test(t)) return "Document"; if (/(story|film|horror|drama|comedy|adventure|quest)/.test(t)) return "Story"; return "Visual"; };

export const categoryCards: CategoryCard[] = titles.map((title, index) => ({ id: index + 1, title, description: `A ready-made ${title.toLowerCase()} prompt with a clear visual hook, production direction, and scene-ready structure.`, kind: chooseKind(title), image: chooseImage(title), accent: accents[index % accents.length], duration: index % 4 === 0 ? "60 sec" : index % 4 === 1 ? "2 min" : index % 4 === 2 ? "3 min" : "5 min" }));
